backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: assets/images

collections:
  - name: "page" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Permalink"
        name: "permalink"
        widget: "string"
        required: false
        pattern: ['\/[-A-Za-z0-9\+&@#%?=~_|!:,.;]*[-A-Za-z0-9\+&@#%=~_|]\/', "de permalink moet een slash voor en na de tekst bevatten"]

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false

      - label: "Menu weight"
        name: "weight"
        widget: "number"
        required: false
        valueType: "int"
        default: 0

      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "_config.yml"
        description: "General Site Settings"
        fields:
          - {label: "Site Naam", name: "name", widget: "string"}
          - label: "Site Beschrijving"
            name: "description"
            widget: "text"
          - label: "Url"
            name: "url"
            widget: "string"
            pattern: ['_^(?:(?:https?|ftp)://)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)(?:\.(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)*(?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,})))(?::\d{2,5})?(?:/[^\s]*)?$_iuS', "Vul een geldige URL in"]
          - {label: "Google Analytics tracking code", name: "google_analytics", widget: "string"}
          - {label: "Basis URL", name: "baseurl", widget: "string"}
          - {label: "Permalink ", name: "permalink", widget: "string"}
          - label: "Plugins"
            name: plugins
            widget: "list"
            default: ["plugin"]
          - label: "Exclude"
            name: exclude
            widget: "list"
            default: ["exclude"]
